version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    
  # Optional: Qdrant dashboard (if you want a web UI)
  qdrant-web-ui:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    depends_on:
      - qdrant
    profiles:
      - web-ui
