#!/usr/bin/env zsh

############################################################
# quick_commit.sh
#
# Quickly add, commit, and push changes to GitHub
#
# Usage:
#     ./quick_commit.sh "commit message"
#     ./quick_commit.sh  # Uses default message with timestamp
#
# Example:
#     ./quick_commit.sh "Add new feature"
#     ./quick_commit.sh
#
# Author: Auto-generated by newproject.sh
############################################################

set -euo pipefail

# Use provided commit message or default with timestamp
if [[ $# -eq 0 ]]; then
    COMMIT_MSG="Update: $(date '+%Y-%m-%d %H:%M:%S')"
elif [[ $# -eq 1 ]]; then
    COMMIT_MSG="$1"
else
    echo "Usage: $0 [commit_message]"
    exit 1
fi

echo "Adding all changes..."
git add .

echo "Committing with message: \"$COMMIT_MSG\""
git commit -m "$COMMIT_MSG"

echo "Pushing to GitHub..."
git push

echo "✅ Changes successfully pushed to GitHub!"
